import { randomUUID } from 'node:crypto';
import { EnquiryValues, fileExtension, validateEnquiry, validateFiles } from '../components/ProjectForm/schema';
import type { SpreadsheetAdapter,SpreadsheetEnquiry } from './integrations/spreadsheet';
export const MAX_PAYLOAD_SIZE=8*20*1024*1024+64*1024; type RateRecord={count:number;reset:number};
export type EnquiryResult={status:number;body:{message:string;requestId:string;errors?:Record<string,string>}};
export type UploadHandler=(files:Array<{file:File;storageName:string}>,enquiryId:string)=>Promise<string[]>;
export type OperationalLogger=(event:Record<string,string>)=>void;
export class EnquiryService{private requests=new Map<string,RateRecord>();constructor(private adapter?:SpreadsheetAdapter,private upload:UploadHandler=files=>files.length?Promise.reject(new Error('upload_storage_unavailable')):Promise.resolve([]),private now=()=>Date.now(),private log:OperationalLogger=event=>console.info(JSON.stringify(event))){}
 async handle(form:FormData,ip='unknown',requestId:string=randomUUID(),enquiryId:string=requestId,source='web-form'):Promise<EnquiryResult>{const current=this.now(),record=this.requests.get(ip);if(record&&record.reset>current&&record.count>=5)return{status:429,body:{message:'Please wait before trying again.',requestId}};this.requests.set(ip,!record||record.reset<=current?{count:1,reset:current+60_000}:{...record,count:record.count+1});const value=(key:string)=>{const entry=form.get(key);return typeof entry==='string'?entry:''};const data:EnquiryValues={fullName:value('fullName'),email:value('email'),phone:value('phone'),postcode:value('postcode'),workType:value('workType'),startDate:value('startDate'),budget:value('budget'),contactMethod:value('contactMethod'),description:value('description'),website:value('website')};
  if(data.website){this.log({event:'enquiry_rejected',requestId,enquiryId,category:'spam'});return{status:200,body:{message:'Enquiry received.',requestId}}}const files=form.getAll('files').filter((entry):entry is File=>typeof entry!=='string'&&entry.size>0);const errors={...validateEnquiry(data)};const fileError=validateFiles(files);if(fileError)errors.files=fileError;if(Object.keys(errors).length){this.log({event:'enquiry_rejected',requestId,enquiryId,category:'validation'});return{status:400,body:{message:'Please check the form and try again.',requestId,errors}}}const safeFiles=files.map(file=>({file,storageName:`${randomUUID()}${fileExtension(file.name)}`}));try{if(!this.adapter)throw new Error('spreadsheet_configuration_missing');const uploadReferences=await this.upload(safeFiles,enquiryId);const enquiry:SpreadsheetEnquiry={enquiryId,receivedAt:new Date(current).toISOString(),...data,uploadReferences,status:'received',metadata:{requestId,source}};await this.adapter.appendEnquiry(enquiry);this.log({event:'enquiry_stored',requestId,enquiryId,category:'success'});return{status:201,body:{message:'Enquiry received.',requestId}}}catch(error){const category=error instanceof Error?error.message:'provider_error';this.log({event:'enquiry_store_failed',requestId,enquiryId,category});return{status:503,body:{message:'We could not process your enquiry. Please try again later.',requestId}}}}
}
