import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { describe, expect, it } from 'vitest';
import { App } from '../App';
import { sectionOrder } from '../content/site';

describe('assembled page', () => {
 it('renders the required anchors in specification order',()=>{ const {container}=render(<App/>); const actual=[...container.querySelectorAll('[id]')].map(n=>n.id).filter(id=>sectionOrder.includes(id as never)); expect(actual).toEqual(sectionOrder); });
 it('uses semantic landmarks and exactly one h1',()=>{render(<App/>);expect(screen.getAllByRole('banner')).toHaveLength(1);expect(screen.getByRole('main')).toBeInTheDocument();expect(screen.getByRole('contentinfo')).toBeInTheDocument();expect(screen.getAllByRole('heading',{level:1})).toHaveLength(1);});
 it('uses the JAY logo in accessible header and footer home links',()=>{const {container}=render(<App/>);const homeLinks=screen.getAllByRole('link',{name:'JAY Builders home'});expect(homeLinks).toHaveLength(2);for(const link of homeLinks){expect(link).toHaveAttribute('href','#home');const logo=link.querySelector('img');expect(logo).toHaveAttribute('src','/assets/images/JayLogo.png');expect(logo).toHaveAttribute('alt','');}expect(container.querySelectorAll('.brand img')).toHaveLength(2);});
 it('renders approved grid content counts',()=>{const {container}=render(<App/>);expect(container.querySelectorAll('.story-card')).toHaveLength(3);expect(container.querySelectorAll('.project-card')).toHaveLength(6);expect(container.querySelectorAll('.service-card')).toHaveLength(8);expect(container.querySelectorAll('.review-card')).toHaveLength(4);expect(container.querySelectorAll('.process-grid li')).toHaveLength(4);});
 it('renders the services guidance card with its decorative work icon and CTA',()=>{const {container}=render(<App/>);const card=container.querySelector('.guidance-card')!;expect(card.querySelector('.guidance-card__icon svg')).toBeInTheDocument();expect(card.querySelector('.guidance-card__icon')).toHaveAttribute('aria-hidden','true');expect(card.querySelector('a')).toHaveAttribute('href','#contact');});
 it('renders the interactive Project Spotlight gallery before the aligned copy and testimonial',()=>{const {container}=render(<App/>);const grid=container.querySelector('#project-spotlight .spotlight-grid')!;const gallery=grid.querySelector('.spotlight-gallery')!;expect(gallery).toBe(grid.firstElementChild);expect(gallery.querySelectorAll('img')).toHaveLength(5);expect(screen.getByAltText('Renovated open-plan kitchen with a central island, dining area and garden doors')).toBeInTheDocument();const thumbnail=screen.getByRole('button',{name:'Show Completed modern bathroom in the renovated home'});fireEvent.mouseEnter(thumbnail);expect(screen.getAllByAltText('Completed modern bathroom in the renovated home')).toHaveLength(2);});
 it('plays the Bathroom Renovation testimonial from the hero and restores focus when closed',async()=>{render(<App/>);const trigger=screen.getByRole('button',{name:'Play Bathroom Renovation customer testimonial'});expect(screen.queryByTitle('Bathroom Renovation customer testimonial video')).not.toBeInTheDocument();fireEvent.click(trigger);expect(screen.getByRole('dialog',{name:'Bathroom Renovation'})).toBeInTheDocument();expect(screen.getByTitle('Bathroom Renovation customer testimonial video')).toHaveAttribute('src','https://www.youtube-nocookie.com/embed/tOwjEOt1zYU?autoplay=1');fireEvent.keyDown(document,{key:'Escape'});await waitFor(()=>expect(screen.queryByTitle('Bathroom Renovation customer testimonial video')).not.toBeInTheDocument());expect(trigger).toHaveFocus();});
 it('opens the named drawer, moves focus, closes with Escape, and restores focus and scrolling',async()=>{render(<App/>);const toggle=screen.getByRole('button',{name:'Open navigation menu'});expect(toggle).toHaveAttribute('aria-expanded','false');fireEvent.click(toggle);expect(toggle).toHaveAttribute('aria-expanded','true');expect(document.body).toHaveStyle({overflow:'hidden'});expect(screen.getByRole('link',{name:'Home'})).toHaveFocus();fireEvent.keyDown(document,{key:'Escape'});await waitFor(()=>expect(toggle).toHaveFocus());expect(toggle).toHaveAttribute('aria-expanded','false');expect(document.body.style.overflow).toBe('');});
 it.each([
  ['Complete Home Renovation', 'pU5kvweq-EE'],
  ['Kitchen Extension', 'Jw7s42Op2ao'],
  ['Bathroom Renovation', 'tOwjEOt1zYU'],
 ])('opens the %s privacy-enhanced video only after activation and restores focus on Escape',async(title,videoId)=>{render(<App/>);const trigger=screen.getByRole('button',{name:`Play ${title} customer story`});expect(screen.queryByTitle(`${title} customer story video`)).not.toBeInTheDocument();trigger.focus();fireEvent.click(trigger);expect(screen.getByRole('dialog',{name:title})).toBeInTheDocument();const iframe=screen.getByTitle(`${title} customer story video`);expect(iframe).toHaveAttribute('src',`https://www.youtube-nocookie.com/embed/${videoId}`);expect(iframe).toHaveAttribute('allowfullscreen');expect(screen.getByRole('button',{name:'Close customer story'})).toHaveFocus();fireEvent.keyDown(document,{key:'Escape'});await waitFor(()=>expect(screen.queryByRole('dialog')).not.toBeInTheDocument());expect(trigger).toHaveFocus();});
 it('connects every link to a present anchor or contact protocol',()=>{const {container}=render(<App/>);container.querySelectorAll<HTMLAnchorElement>('a[href]').forEach(link=>{const target=link.getAttribute('href')!;if(target.startsWith('#')) expect(document.querySelector(target),target).toBeInTheDocument();else expect(target).toMatch(/^(tel:|mailto:)/);});});
 it('places urgent assistance beside the lower main content',()=>{const {container}=render(<App/>);const grid=container.querySelector('.lower-grid')!;expect(grid.children[0]).toHaveClass('lower-main');expect(grid.children[1]).toHaveClass('urgent-column');expect(grid.children[1].querySelector('#urgent-assistance')).toBeInTheDocument();});
 it('offers only the urgent enquiry CTA before the van image',()=>{const {container}=render(<App/>);const card=container.querySelector('#urgent-assistance')!;expect(screen.queryByText('Call JAY Builders')).not.toBeInTheDocument();const enquiry=screen.getByRole('link',{name:'Send an urgent property assistance enquiry'});expect(enquiry).toHaveTextContent('Send an Urgent Enquiry');expect(enquiry).toHaveAttribute('href','#contact');expect(card.querySelectorAll('.urgent-enquiry-button')).toHaveLength(1);expect(card.lastElementChild).toHaveClass('urgent-media');});
});
