/* eslint-disable @typescript-eslint/no-unsafe-member-access */
import { describe,expect,it,vi } from 'vitest';
import { fireEvent,render,screen,waitFor } from '@testing-library/react';
import { ProjectForm } from '../components/ProjectForm';
import { allowedMimeTypes,budgetOptions,contactOptions,emptyEnquiry,MAX_FILES,MAX_FILE_SIZE,startOptions,validateEnquiry,validateFiles,workOptions } from '../components/ProjectForm/schema';
import { EnquiryService } from '../server/enquiries';
const valid={...emptyEnquiry,fullName:'Jane Builder',email:'jane@example.com',phone:'020 7946 0123',postcode:'SW1A 1AA',workType:workOptions[0],contactMethod:contactOptions[0],description:'A sufficiently detailed project description.'};
const form=()=>{const f=new FormData();Object.entries(valid).forEach(([k,v])=>f.set(k,v));return f};
describe('shared enquiry schema',()=>{
 it.each(['fullName','email','phone','postcode','workType','contactMethod','description'] as const)('validates %s',key=>{expect(validateEnquiry({...valid,[key]:''})).toHaveProperty(key)});
 it.each(workOptions)('accepts work option %s',workType=>expect(validateEnquiry({...valid,workType}).workType).toBeUndefined());
 it.each(startOptions)('accepts start option %s',startDate=>expect(validateEnquiry({...valid,startDate}).startDate).toBeUndefined());
 it.each(budgetOptions)('accepts budget option %s',budget=>expect(validateEnquiry({...valid,budget}).budget).toBeUndefined());
 it.each(contactOptions)('accepts contact option %s',contactMethod=>expect(validateEnquiry({...valid,contactMethod}).contactMethod).toBeUndefined());
 it.each(allowedMimeTypes)('accepts MIME %s',type=>{const extensions:Record<string,string>={'image/jpeg':'.jpg','image/png':'.png','image/webp':'.webp','video/mp4':'.mp4','video/quicktime':'.mov'};expect(validateFiles([new File(['x'],'photo'+extensions[type],{type})])).toBeUndefined()});
 it('checks file count and size boundaries',()=>{const file=new File(['x'], 'x.jpg',{type:'image/jpeg'});expect(validateFiles(Array(MAX_FILES).fill(file))).toBeUndefined();expect(validateFiles(Array(MAX_FILES+1).fill(file))).toMatch(/no more/);expect(validateFiles([new File([new Uint8Array(MAX_FILE_SIZE)],'x.jpg',{type:'image/jpeg'})])).toBeUndefined();expect(validateFiles([new File([new Uint8Array(MAX_FILE_SIZE+1)],'x.jpg',{type:'image/jpeg'})])).toMatch(/20 MB/)});
 it('rejects extension and MIME mismatches',()=>{expect(validateFiles([new File(['x'],'x.exe',{type:'image/jpeg'})])).toBeTruthy();expect(validateFiles([new File(['x'],'x.jpg',{type:'text/plain'})])).toBeTruthy()});
});
describe('server protections',()=>{const adapter=()=>({appendEnquiry:vi.fn().mockResolvedValue('appended' as const)});it('never appends honeypot or invalid submissions',async()=>{const sheet=adapter(),service=new EnquiryService(sheet,undefined,undefined,()=>{});const spam=form();spam.set('website','spam');expect((await service.handle(spam)).status).toBe(200);expect((await service.handle(new FormData())).status).toBe(400);expect(sheet.appendEnquiry).not.toHaveBeenCalled()});it('rate limits the sixth request',async()=>{const service=new EnquiryService(adapter(),undefined,undefined,()=>{});for(let i=0;i<5;i++)expect((await service.handle(form(),'ip',String(i))).status).toBe(201);expect((await service.handle(form(),'ip')).status).toBe(429)});it('uploads before appending and returns a retryable provider failure',async()=>{const sheet=adapter(),upload=vi.fn().mockResolvedValue(['private-object:one']),f=form();f.append('files',new File(['x'],'../../private.jpg',{type:'image/jpeg'}));expect((await new EnquiryService(sheet,upload,()=>0,()=>{}).handle(f,'ip','request','enquiry')).status).toBe(201);expect(upload.mock.calls[0][0][0].storageName).toMatch(/^[\w-]+\.jpg$/);expect(sheet.appendEnquiry.mock.calls[0][0].uploadReferences).toEqual(['private-object:one']);sheet.appendEnquiry.mockRejectedValueOnce(new Error('spreadsheet_append_failed'));expect((await new EnquiryService(sheet,undefined,undefined,()=>{}).handle(form())).status).toBe(503)})});
describe('accessible form submission',()=>{it('announces errors',async()=>{render(<ProjectForm/>);fireEvent.click(screen.getByRole('button'));expect(await screen.findByRole('alert')).toHaveTextContent('There is a problem');expect(screen.getByRole('status')).toHaveTextContent('correct')});it('prevents duplicates and announces success',async()=>{let resolve!:(v:Response)=>void;vi.stubGlobal('fetch',vi.fn(()=>new Promise<Response>(r=>resolve=r)));render(<ProjectForm/>);for(const [name,value] of Object.entries(valid)){const element=document.querySelector(`[name="${name}"]`);if(element)fireEvent.change(element,{target:{value}})}const button=screen.getByRole('button');fireEvent.click(button);fireEvent.click(button);expect(fetch).toHaveBeenCalledTimes(1);resolve(new Response('{}',{status:201}));await waitFor(()=>expect(screen.getByRole('status')).toHaveTextContent('Thank you'))})});
