/* eslint-disable @typescript-eslint/no-unsafe-member-access, @typescript-eslint/require-await */
import { describe,expect,it,vi } from 'vitest';
import { fireEvent,render,screen,waitFor } from '@testing-library/react';
import { ProjectForm } from '../components/ProjectForm';
import { allowedMimeTypes,budgetOptions,contactOptions,emptyEnquiry,MAX_FILES,MAX_FILE_SIZE,startOptions,validateEnquiry,validateFiles,workOptions } from '../components/ProjectForm/schema';
import { EnquiryService } from '../server/enquiries';
const valid={...emptyEnquiry,fullName:'Jane Builder',email:'jane@example.com',phone:'020 7946 0123',postcode:'SW1A 1AA',workType:workOptions[0],contactMethod:contactOptions[0],description:'A sufficiently detailed project description.'};
const form=()=>{const f=new FormData();Object.entries(valid).forEach(([k,v])=>f.set(k,v));return f};
describe('shared enquiry schema',()=>{
 it.each(['fullName','email','phone','postcode','workType','contactMethod','description'] as const)('validates %s',key=>{expect(validateEnquiry({...valid,[key]:''})).toHaveProperty(key)});
 it.each(workOptions)('accepts work option %s',workType=>expect(validateEnquiry({...valid,workType}).workType).toBeUndefined());
 it.each(startOptions)('accepts start option %s',startDate=>expect(validateEnquiry({...valid,startDate}).startDate).toBeUndefined());
 it.each(budgetOptions)('accepts budget option %s',budget=>expect(validateEnquiry({...valid,budget}).budget).toBeUndefined());
 it.each(contactOptions)('accepts contact option %s',contactMethod=>expect(validateEnquiry({...valid,contactMethod}).contactMethod).toBeUndefined());
 it.each(allowedMimeTypes)('accepts MIME %s',type=>{const extensions:Record<string,string>={'image/jpeg':'.jpg','image/png':'.png','image/webp':'.webp','video/mp4':'.mp4','video/quicktime':'.mov'};expect(validateFiles([new File(['x'],'photo'+extensions[type],{type})])).toBeUndefined()});
 it('checks file count and size boundaries',()=>{const file=new File(['x'], 'x.jpg',{type:'image/jpeg'});expect(validateFiles(Array(MAX_FILES).fill(file))).toBeUndefined();expect(validateFiles(Array(MAX_FILES+1).fill(file))).toMatch(/no more/);expect(validateFiles([new File([new Uint8Array(MAX_FILE_SIZE)],'x.jpg',{type:'image/jpeg'})])).toBeUndefined();expect(validateFiles([new File([new Uint8Array(MAX_FILE_SIZE+1)],'x.jpg',{type:'image/jpeg'})])).toMatch(/20 MB/)});
 it('rejects extension and MIME mismatches',()=>{expect(validateFiles([new File(['x'],'x.exe',{type:'image/jpeg'})])).toBeTruthy();expect(validateFiles([new File(['x'],'x.jpg',{type:'text/plain'})])).toBeTruthy()});
});
describe('server protections',()=>{it('silently accepts honeypot without saving',async()=>{const save=vi.fn();const f=form();f.set('website','spam');expect((await new EnquiryService(undefined,save).handle(f)).status).toBe(200);expect(save).not.toHaveBeenCalled()});it('rate limits the sixth request',async()=>{const service=new EnquiryService();for(let i=0;i<5;i++)expect((await service.handle(form(),'ip')).status).toBe(201);expect((await service.handle(form(),'ip')).status).toBe(429)});it('uses safe storage names and handles storage failure',async()=>{const save=vi.fn().mockResolvedValue(undefined);const f=form();f.append('files',new File(['x'],'../../private.jpg',{type:'image/jpeg'}));expect((await new EnquiryService(undefined,save).handle(f)).status).toBe(201);expect(save.mock.calls[0][1][0].storageName).toMatch(/^[\w-]+\.jpg$/);expect((await new EnquiryService(undefined,async()=>{throw Error()}).handle(form())).status).toBe(500)})});
describe('accessible form submission',()=>{it('announces errors',async()=>{render(<ProjectForm/>);fireEvent.click(screen.getByRole('button'));expect(await screen.findByRole('alert')).toHaveTextContent('There is a problem');expect(screen.getByRole('status')).toHaveTextContent('correct')});it('prevents duplicates and announces success',async()=>{let resolve!:(v:Response)=>void;global.fetch=vi.fn(()=>new Promise(r=>resolve=r));render(<ProjectForm/>);for(const [name,value] of Object.entries(valid)){const element=document.querySelector(`[name="${name}"]`);if(element)fireEvent.change(element,{target:{value}})}const button=screen.getByRole('button');fireEvent.click(button);fireEvent.click(button);expect(fetch).toHaveBeenCalledTimes(1);resolve(new Response('{}',{status:201}));await waitFor(()=>expect(screen.getByRole('status')).toHaveTextContent('Thank you'))})});
